version: '2'
services:
  alexandria:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/alexandria:latest
    entrypoint:
      - java
      - -jar
      - /app/alexandria.jar
      - --keyspace=alexandria_dev
      - --cassandra_hosts=cassandra
      - --matches_bucket=matches-dev
    links:
      - cassandra
    ports:
      - "22045:22045"
      - "22046:22046"

  cassandra:
    image: cassandra:3.9
    volumes:
      - /asuna/volume0:/var/lib/cassandra
    ports:
      - "7000-7001:7000-7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

  charon:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/charon:latest
    entrypoint:
      - java
      - -jar
      - /app/charon-assembly.jar
      - --riot_api_key=${CHARON_RIOT_KEY}
      - --req_per_10min=180000
      - --req_per_10sec=3000
      - --capacity_multiplier=0.8
    ports:
      - "5609:5609"
      - "5610:5610"

  helios:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/helios:latest
    entrypoint:
      - ./helios
      - --lucinda_host=lucinda:45045
      - --vulgate_host=vulgate:6205
    links:
      - lucinda
      - vulgate
    ports:
      - "7921:7921"
      - "7922:7922" 

  legends.ai:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/legends.ai:latest
    entrypoint:
      - node
      - build/server.js
    ports:
      - "7448:7448"
    environment:
      - PORT=7448

  lucinda:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/lucinda:latest
    entrypoint:
      - java
      - -jar
      - /app/lucinda-assembly.jar
      - --cassandra_hosts=cassandra
      - --redis_host=lucinda-cache
      - --vulgate_host=vulgate
      - --vulgate_port=6205
    links:
      - cassandra
      - lucinda-cache
      - vulgate
    ports:
      - "45045:45045"
      - "45046:45046"

  lucinda-cache:
    image: redis:3.2.5

  nova:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/nova:latest
    entrypoint:
      - java
      - -jar
      - /app/nova-assembly.jar
      - --redis_host=nova-queue
      - --redis_port=6379
      - --ingest_max_interval=60
      - --ingest_max_batch_size=60
      - --alexandria_host=alexandria
      - --alexandria_port=22045
      - --charon_host=charon
      - --charon_port=5609
    links:
      - alexandria
      - charon
      - nova-queue

  nova-queue:
    image: redis:3.2.5

  vulgate:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/vulgate:latest
    entrypoint:
      - java
      - -jar
      - /app/vulgate-assembly.jar
      - --charon_host=charon
      - --charon_port=5609
      - --redis_host=vulgate-cache
      - --redis_port=6379
    links:
      - charon
      - vulgate-cache
    ports:
      - "6205:6205"
      - "6206:6206"

  vulgate-cache:
    image: redis:3.2.5
