version: '2'
services:
  bacchus:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/bacchus:latest
    entrypoint: ./bacchus
    ports:
      - "9730:9730"
      - "9731:9731"
    links:
      - bacchus-queue
      - cassandra
      - charon
    environment:
      - BACCHUS_ATHENA_HOSTS=cassandra
      - BACCHUS_CHARON_HOST=charon:5609
      - BACCHUS_REDIS_HOST=bacchus-queue:6379

  bacchus-queue:
    image: redis:3.2.5

  cassandra:
    image: cassandra:3.9
    volumes:
      - /asuna/volume0:/var/lib/cassandra
    ports:
      - "7000-7001:7000-7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

  charon:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/charon:latest
    entrypoint: ./charon
    ports:
      - "5609:5609"
      - "5610:5610"
    environment:
      - CHARON_APIKEY
      - CHARON_MAX_RATE=3334000ns

  helios:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/helios:latest
    depends_on:
      - lucinda
    entrypoint:
      - ./helios
      - --lucinda_host=lucinda:45045
    ports:
      - "7921:7921"
      - "7922:7922" 

  lucinda:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/lucinda:latest
    entrypoint:
      - java
      - -jar
      - /app/lucinda-assembly.jar
      - --lucinda_port=45045
    links:
      - cassandra
      - lucinda-cache
    ports:
      - "45045:45045"
      - "45046:45046"

  lucinda-cache:
    image: redis:3.2.5

  vulgate:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/vulgate:latest
    entrypoint:
      - java
      - -jar
      - /app/vulgate-assembly.jar
      - --vulgate_port=6205
    links:
      - vulgate-cache
    ports:
      - "6205:6205"
      - "6206:6206"

  vulgate-cache:
    image: redis:3.2.5
