version: '2'
services:
  athena:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/athena:latest
    entrypoint:
      - spark-submit
      - --conf
      - spark.cassandra.connection.host=cassandra
      - --class
      - ai.legends.athena.Main
      - --master
      - local[4]
      - /app/athena-assembly.jar
    links:
      - cassandra

  bacchus:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/bacchus:latest
    entrypoint: ./bacchus
    ports:
      - "9730:9730"
      - "9731:9731"
    links:
      - bacchus-queue
      - cassandra
      - charon
      - totsuki
    environment:
      - BACCHUS_CASSANDRA_HOSTS=cassandra
      - BACCHUS_CHARON_HOST=charon:5609
      - BACCHUS_REDIS_HOST=bacchus-queue:6379
      - BACCHUS_TOTSUKI_HOST=totsuki:21215

  bacchus-queue:
    image: redis:3.2.5

  cassandra:
    image: cassandra:3.9
    volumes:
      - /asuna/volume0:/var/lib/cassandra
    ports:
      - "7000-7001:7000-7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

  charon:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/charon:latest
    entrypoint:
      - java
      - -jar
      - /app/charon-assembly.jar
      - --riot_api_key=${CHARON_RIOT_KEY}
      - --req_per_10min=180000
      - --req_per_10sec=3000
      - --capacity_multiplier=0.8
    ports:
      - "5609:5609"
      - "5610:5610"

  helios:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/helios:latest
    entrypoint:
      - ./helios
      - --lucinda_host=lucinda:45045
      - --vulgate_host=vulgate:6205
    links:
      - lucinda
      - vulgate
    ports:
      - "7921:7921"
      - "7922:7922" 

  jibril:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/jibril:latest
    entrypoint:
      - java
      - -jar
      - /app/jibril.jar
      - --lock_bucket=athena-locks-dev
      - --matches_bucket=matches-dev
      - --fragments_bucket=totsuki-fragments-dev
      - --cassandra_hosts=cassandra
    ports:
      - "30493:30493"
      - "30494:30494"
    links:
      - cassandra


  legends.ai:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/legends.ai:latest
    entrypoint:
      - node
      - build/server.js
    ports:
      - "7448:7448"
    environment:
      - PORT=7448

  lucinda:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/lucinda:latest
    entrypoint:
      - java
      - -jar
      - /app/lucinda-assembly.jar
      - --cassandra_hosts=cassandra
      - --redis_host=lucinda-cache
      - --vulgate_host=vulgate
      - --vulgate_port=6205
    links:
      - cassandra
      - lucinda-cache
      - vulgate
    ports:
      - "45045:45045"
      - "45046:45046"

  lucinda-cache:
    image: redis:3.2.5

  totsuki:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/totsuki:latest
    entrypoint:
      - java
      - -jar
      - /app/totsuki-assembly.jar
      - --bucket=totsuki-fragments-dev
    ports:
      - "21215:21215"
      - "21216:21216"

  vulgate:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/vulgate:latest
    entrypoint:
      - java
      - -jar
      - /app/vulgate-assembly.jar
      - --charon_host=charon
      - --charon_port=5609
      - --redis_host=vulgate-cache
      - --redis_port=6379
    links:
      - charon
      - vulgate-cache
    ports:
      - "6205:6205"
      - "6206:6206"

  vulgate-cache:
    image: redis:3.2.5
