version: '2'
services:
  athena:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/athena:latest
    entrypoint:
      - spark-submit
      - --conf
      - spark.cassandra.connection.host=cassandra
      - --class
      - ai.legends.athena.Main
      - --master
      - local[4]
      - /app/athena-assembly.jar
    links:
      - cassandra

  bacchus:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/bacchus:latest
    entrypoint: ./bacchus
    ports:
      - "9730:9730"
      - "9731:9731"
    links:
      - bacchus-queue
      - cassandra
      - charon
    environment:
      - BACCHUS_ATHENA_HOSTS=cassandra
      - BACCHUS_CHARON_HOST=charon:5609
      - BACCHUS_REDIS_HOST=bacchus-queue:6379

  bacchus-queue:
    image: redis:3.2.5

  cassandra:
    image: cassandra:3.9
    volumes:
      - /asuna/volume0:/var/lib/cassandra
    ports:
      - "7000-7001:7000-7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

  charon:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/charon:latest
    entrypoint:
      - ./charon
      - --riot_key=${CHARON_RIOT_KEY}
      - --max_rate=3334000ns
    ports:
      - "5609:5609"
      - "5610:5610"

  helios:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/helios:latest
    entrypoint:
      - ./helios
      - --lucinda_host=lucinda:45045
      - --vulgate_host=vulgate:6205
    links:
      - lucinda
      - vulgate
    ports:
      - "7921:7921"
      - "7922:7922" 

  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"

  lucinda:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/lucinda:latest
    entrypoint:
      - java
      - -jar
      - /app/lucinda-assembly.jar
      - --cassandra_hosts=cassandra
      - --redis_host=lucinda-cache
      - --vulgate_host=vulgate
      - --vulgate_port=6205
    links:
      - cassandra
      - lucinda-cache
      - vulgate
    ports:
      - "45045:45045"
      - "45046:45046"

  lucinda-cache:
    image: redis:3.2.5

  vulgate:
    image: 096202052535.dkr.ecr.us-west-2.amazonaws.com/vulgate:latest
    entrypoint:
      - java
      - -jar
      - /app/vulgate-assembly.jar
      - --charon_host=charon
      - --charon_port=5609
      - --redis_host=vulgate-cache
      - --redis_port=6379
    links:
      - charon
      - vulgate-cache
    ports:
      - "6205:6205"
      - "6206:6206"

  vulgate-cache:
    image: redis:3.2.5
